<?php
/**
 * @file
 * pharmtrac_ndc.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function pharmtrac_ndc_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'vid\' => \'1798\',
      \'uid\' => \'1\',
      \'title\' => \'Check NDC\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'1\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'614edabe-5f6b-0d34-75fc-56b899024ba9\',
      \'nid\' => \'1798\',
      \'type\' => \'medfeature\',
      \'language\' => \'und\',
      \'created\' => \'1365535367\',
      \'changed\' => \'1365535367\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'8b317854-8869-5564-1173-154d74e6e6c7\',
      \'revision_timestamp\' => \'1365535367\',
      \'revision_uid\' => \'1\',
      \'body\' => array(),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1365535367\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'comment_count\' => \'0\',
      \'name\' => \'administrator\',
      \'picture\' => \'0\',
      \'data\' => \'b:0;\',
      \'menu\' => NULL,
      \'path\' => FALSE,
      \'node_export_drupal_version\' => \'7\',
    ),
)',
);
  return $node_export;
}
