<?php
/**
 * @file
 * abc.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function abc_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'vid\' => \'1750\',
      \'uid\' => \'1\',
      \'title\' => \'test\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'2\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'f425fb28-3817-e524-cd4d-d481eb2e27f2\',
      \'nid\' => \'1750\',
      \'type\' => \'portal_feature\',
      \'language\' => \'und\',
      \'created\' => \'1362681546\',
      \'changed\' => \'1362681546\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'8fc819f6-3155-b1e4-f1e9-4bd7f0d2a63a\',
      \'revision_timestamp\' => \'1362681546\',
      \'revision_uid\' => \'1\',
      \'body\' => array(),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1362681546\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'comment_count\' => \'0\',
      \'name\' => \'administrator\',
      \'picture\' => \'0\',
      \'data\' => \'b:0;\',
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
)',
);
  return $node_export;
}
